//
//  GeneratedComponentSources.swift
//  MwohamMac
//
//  Generated by scripts/build_component_assets.sh.
//

import Foundation

nonisolated enum ComponentSourceCatalog {
    static let v1_1_0 = ComponentDownloadConfig(
        version: "1.1.0",
        baseURLString: "https://github.com/ing2720/mwoham/releases/download/v1.1.0",
        sha256ByComponent: [
            .backend: "cc3b2b8d9b5f613ef14a950b0861b2e2a186f0a14721ba916733e8fc20971d33",
            .sttCLI: "a1b9e5e354a0e48df6c6d07e270aa7afbecef450fc770a8c82c295c3db1823da",
            .sttModel: "1fc70f774d38eb169993ac391eea357ef47c88757ef72ee5943879b7e8e2bc69",
        ],
        urlByComponent: [
            .backend: "https://github.com/ing2720/mwoham/releases/download/v1.1.0/MwohamBackend-1.1.0.tar.gz?sha256=cc3b2b8d9b5f613ef14a950b0861b2e2a186f0a14721ba916733e8fc20971d33",
            .sttCLI: "https://github.com/ing2720/mwoham/releases/download/v1.1.0/MwohamSTTRuntime-1.1.0.tar.gz?sha256=a1b9e5e354a0e48df6c6d07e270aa7afbecef450fc770a8c82c295c3db1823da",
            .sttModel: "https://github.com/ing2720/mwoham/releases/download/v1.1.0/ggml-large-v3-turbo.bin?sha256=1fc70f774d38eb169993ac391eea357ef47c88757ef72ee5943879b7e8e2bc69",
        ]
    )
}
