"""add screen observations table

Revision ID: 1d85442bd6f8
Revises: 71ecd612fc54
Create Date: 2026-05-27 13:04:52.306703

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1d85442bd6f8"
down_revision: str | None = "71ecd612fc54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screen_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("app_name", sa.String(length=100), nullable=True),
        sa.Column("window_title", sa.String(length=255), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("detected_keywords", sa.JSON(), nullable=True),
        sa.Column("ai_inference", sa.Text(), nullable=True),
        sa.Column("frame_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["work_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screen_observations_app_name"), "screen_observations", ["app_name"], unique=False
    )
    op.create_index(
        op.f("ix_screen_observations_frame_hash"),
        "screen_observations",
        ["frame_hash"],
        unique=False,
    )
    op.create_index(op.f("ix_screen_observations_id"), "screen_observations", ["id"], unique=False)
    op.create_index(
        op.f("ix_screen_observations_session_id"),
        "screen_observations",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screen_observations_timestamp"), "screen_observations", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_screen_observations_timestamp"), table_name="screen_observations")
    op.drop_index(op.f("ix_screen_observations_session_id"), table_name="screen_observations")
    op.drop_index(op.f("ix_screen_observations_id"), table_name="screen_observations")
    op.drop_index(op.f("ix_screen_observations_frame_hash"), table_name="screen_observations")
    op.drop_index(op.f("ix_screen_observations_app_name"), table_name="screen_observations")
    op.drop_table("screen_observations")
    # ### end Alembic commands ###
