"""add settings and private apps

Revision ID: 1dc18634be69
Revises: 1d85442bd6f8
Create Date: 2026-05-27 14:06:02.836902

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1dc18634be69"
down_revision: str | None = "1d85442bd6f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("value_type", sa.String(length=20), server_default="string", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_settings_id"), "app_settings", ["id"], unique=False)
    op.create_index(op.f("ix_app_settings_key"), "app_settings", ["key"], unique=True)
    op.create_table(
        "private_apps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_name", sa.String(length=100), nullable=False),
        sa.Column("match_type", sa.String(length=20), server_default="exact", nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_private_apps_app_name"), "private_apps", ["app_name"], unique=True)
    op.create_index(op.f("ix_private_apps_id"), "private_apps", ["id"], unique=False)
    op.create_index(
        op.f("ix_private_apps_is_enabled"), "private_apps", ["is_enabled"], unique=False
    )
    op.create_index(
        op.f("ix_private_apps_match_type"), "private_apps", ["match_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_private_apps_match_type"), table_name="private_apps")
    op.drop_index(op.f("ix_private_apps_is_enabled"), table_name="private_apps")
    op.drop_index(op.f("ix_private_apps_id"), table_name="private_apps")
    op.drop_index(op.f("ix_private_apps_app_name"), table_name="private_apps")
    op.drop_table("private_apps")
    op.drop_index(op.f("ix_app_settings_key"), table_name="app_settings")
    op.drop_index(op.f("ix_app_settings_id"), table_name="app_settings")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
