"""add reports table

Revision ID: 71ecd612fc54
Revises: feda99c1bfb3
Create Date: 2026-05-27 10:01:33.482322

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "71ecd612fc54"
down_revision: str | None = "feda99c1bfb3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_range_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_range_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=20), server_default="system", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_created_by"), "reports", ["created_by"], unique=False)
    op.create_index(op.f("ix_reports_date"), "reports", ["date"], unique=False)
    op.create_index(op.f("ix_reports_id"), "reports", ["id"], unique=False)
    op.create_index(op.f("ix_reports_mode"), "reports", ["mode"], unique=False)
    op.create_index(op.f("ix_reports_project_id"), "reports", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_reports_source_range_end"), "reports", ["source_range_end"], unique=False
    )
    op.create_index(
        op.f("ix_reports_source_range_start"), "reports", ["source_range_start"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_source_range_start"), table_name="reports")
    op.drop_index(op.f("ix_reports_source_range_end"), table_name="reports")
    op.drop_index(op.f("ix_reports_project_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_mode"), table_name="reports")
    op.drop_index(op.f("ix_reports_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_date"), table_name="reports")
    op.drop_index(op.f("ix_reports_created_by"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
