"""add meetings and transcripts

Revision ID: a3e489b00017
Revises: 1dc18634be69
Create Date: 2026-05-27 14:44:08.583335

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a3e489b00017"
down_revision: str | None = "1dc18634be69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meeting_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meeting_app", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("transcript_enabled", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["work_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meeting_sessions_ended_at"), "meeting_sessions", ["ended_at"], unique=False
    )
    op.create_index(op.f("ix_meeting_sessions_id"), "meeting_sessions", ["id"], unique=False)
    op.create_index(
        op.f("ix_meeting_sessions_meeting_app"), "meeting_sessions", ["meeting_app"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_sessions_session_id"), "meeting_sessions", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_sessions_started_at"), "meeting_sessions", ["started_at"], unique=False
    )
    op.create_table(
        "voice_transcripts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("speaker", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["meeting_id"], ["meeting_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voice_transcripts_id"), "voice_transcripts", ["id"], unique=False)
    op.create_index(
        op.f("ix_voice_transcripts_meeting_id"), "voice_transcripts", ["meeting_id"], unique=False
    )
    op.create_index(
        op.f("ix_voice_transcripts_timestamp"), "voice_transcripts", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_transcripts_timestamp"), table_name="voice_transcripts")
    op.drop_index(op.f("ix_voice_transcripts_meeting_id"), table_name="voice_transcripts")
    op.drop_index(op.f("ix_voice_transcripts_id"), table_name="voice_transcripts")
    op.drop_table("voice_transcripts")
    op.drop_index(op.f("ix_meeting_sessions_started_at"), table_name="meeting_sessions")
    op.drop_index(op.f("ix_meeting_sessions_session_id"), table_name="meeting_sessions")
    op.drop_index(op.f("ix_meeting_sessions_meeting_app"), table_name="meeting_sessions")
    op.drop_index(op.f("ix_meeting_sessions_id"), table_name="meeting_sessions")
    op.drop_index(op.f("ix_meeting_sessions_ended_at"), table_name="meeting_sessions")
    op.drop_table("meeting_sessions")
    # ### end Alembic commands ###
