"""create initial worklog tables

Revision ID: feda99c1bfb3
Revises:
Create Date: 2026-05-26 14:06:22.622388

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "feda99c1bfb3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.create_table(
        "work_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_sessions_ended_at"), "work_sessions", ["ended_at"], unique=False)
    op.create_index(op.f("ix_work_sessions_id"), "work_sessions", ["id"], unique=False)
    op.create_index(
        op.f("ix_work_sessions_project_id"), "work_sessions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_sessions_started_at"), "work_sessions", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_work_sessions_status"), "work_sessions", ["status"], unique=False)
    op.create_table(
        "manual_memos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("linked_type", sa.String(length=50), nullable=True),
        sa.Column("linked_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["work_sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manual_memos_id"), "manual_memos", ["id"], unique=False)
    op.create_index(op.f("ix_manual_memos_linked_id"), "manual_memos", ["linked_id"], unique=False)
    op.create_index(
        op.f("ix_manual_memos_linked_type"), "manual_memos", ["linked_type"], unique=False
    )
    op.create_index(
        op.f("ix_manual_memos_session_id"), "manual_memos", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_manual_memos_timestamp"), "manual_memos", ["timestamp"], unique=False)
    op.create_table(
        "work_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("app_name", sa.String(length=100), nullable=True),
        sa.Column("window_title", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("project_name", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["work_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_events_app_name"), "work_events", ["app_name"], unique=False)
    op.create_index(op.f("ix_work_events_id"), "work_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_work_events_project_name"), "work_events", ["project_name"], unique=False
    )
    op.create_index(op.f("ix_work_events_session_id"), "work_events", ["session_id"], unique=False)
    op.create_index(op.f("ix_work_events_source"), "work_events", ["source"], unique=False)
    op.create_index(op.f("ix_work_events_timestamp"), "work_events", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_events_timestamp"), table_name="work_events")
    op.drop_index(op.f("ix_work_events_source"), table_name="work_events")
    op.drop_index(op.f("ix_work_events_session_id"), table_name="work_events")
    op.drop_index(op.f("ix_work_events_project_name"), table_name="work_events")
    op.drop_index(op.f("ix_work_events_id"), table_name="work_events")
    op.drop_index(op.f("ix_work_events_app_name"), table_name="work_events")
    op.drop_table("work_events")
    op.drop_index(op.f("ix_manual_memos_timestamp"), table_name="manual_memos")
    op.drop_index(op.f("ix_manual_memos_session_id"), table_name="manual_memos")
    op.drop_index(op.f("ix_manual_memos_linked_type"), table_name="manual_memos")
    op.drop_index(op.f("ix_manual_memos_linked_id"), table_name="manual_memos")
    op.drop_index(op.f("ix_manual_memos_id"), table_name="manual_memos")
    op.drop_table("manual_memos")
    op.drop_index(op.f("ix_work_sessions_status"), table_name="work_sessions")
    op.drop_index(op.f("ix_work_sessions_started_at"), table_name="work_sessions")
    op.drop_index(op.f("ix_work_sessions_project_id"), table_name="work_sessions")
    op.drop_index(op.f("ix_work_sessions_id"), table_name="work_sessions")
    op.drop_index(op.f("ix_work_sessions_ended_at"), table_name="work_sessions")
    op.drop_table("work_sessions")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
